// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prsoqlengbcltiinlsri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByc29xbGVuZ2JjbHRpaW5sc3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDA2MjUsImV4cCI6MjA2ODkxNjYyNX0.Y4tDso_S6yF_GagrY6TOLcrfINrfklGIgkNlrlAP4zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});